### ISSUE TITLE
Applying a led profile at launch of container

### ISSUE THREAD

**Issue by kprinssu** [P3R-CO/openrgb-container#1]
I currently have the P3R OpenRGB container to run at boot of my Unraid server. To enable my saved profile, which is to turn off the LEDs on the motherboard, I need to manually go onto the webpage and load the profile.

It looks CalcProgrammer1 (author of OpenRGB) has CLI parameters to specify and apply the profile (see: https://old.reddit.com/r/linux/comments/fqvfbg/openrgb_01_a_new_way_to_control_your_rgb_devices/flsu9zy/). The exact command is `./OpenRGB --profile saved_profile.orp`

Perhaps we can set up a Docker ENV var to do so?

**Comment by kprinssu** [comment]
Solved this by changing startapp.sh to the following:

```
#!/bin/sh
default=$(cat /config/default.txt)
exec /usr/src/openrgb/OpenRGB --server --gui --profile $default
```

Then creating default.txt (inside `/mnt/user/appdata/P3R-OpenRGB` or where ever the Unraid appdata is):
```
/config/xdg/config/OpenRGB/REPLACE_ME_WITH_PROFILE_NAME.orp
```

**Comment by kprinssu** [comment]
Spun up PR https://github.com/P3R-CO/openrgb-container/pull/2 to address this.

**Comment by CaptainASIC** [comment]
added.  sorry for the delays!
